# Plugin created and developed by ImBaeAndItsOk.
# V 1.0
# Want a custom plugin? https://www.spigotmc.org/members/imbaeanditsok.148869/
# Keep in note that this is a side project and not one of my big projects. I will update it as I feel needed.
# You can use any "&(number) color codes in your welcome message.
Welcome Message: '&6Hello and welcome to &3(yourservername). &6Enjoy your stay.'